[main]
    description = "Kokkos is a performance portable programming ecosystem for writing parallel applications that run efficiently across CPUs and GPUs from multiple vendors."

[sharing]
  enabled = true

[home]
  sections = ["blog"]

[schema]
    name = "Kokkos"
    github = "https://github.com/kokkos/kokkos"
    [schema.author]
        name = "The Kokkos Team"

[favicon]
    logo = "img/kokkos-favicon.png"

[style]
    primary = "#2596be"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"

[navigation]
    anchor = true
    logo = "/download/logos/kokkos_text.svg"
    logo-mode = false
    logo-align = "center"
    logo-height = 30
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.7rem"
    breadcrumb = false
    toc = true
    sidebar = true
    sidebarIcons = false
    sidebarIconLevel = 1
    size = "md"
    startLevel = 2
    endLevel = 3
    maxNumHeadings = 9
    [navigation.padding]
        x = 4
        y = 4
    [navigation.search]
        enabled = true
        modal = false
