---
name: Website tests

on:
  pull_request: # To be removed
  schedule:
    - cron: "0 1 * * 1"  # every Monday at 1am
  workflow_dispatch:

jobs:
  links-check:
    name: Links check using linkchecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install linkchecker
        run: |
          pipx install linkchecker
      - name: Analysing the links of the website
        run: |
          linkchecker --check-extern --config=.linkcheckerrc --no-status https://kokkos.org
